### PR TITLE
#299 Moved gpg keyserver and homedir keys up in hash

### PR DESCRIPTION
**Pull request by lesniakania**
I changed this according to this suggestion: https://github.com/fnichol/chef-rvm/commit/72eb4330ea6e181da4b67e3b4e00ece04d71eb88#commitcomment-9685499

### CODE REVIEW

**Comment by plu** [comment]
Would be nice to get this merged into `master`...

**Comment by cmluciano** [comment]
This LGTM, @martinisoft what do you think?

**Comment by tagomoris** [comment]
:+1: I also saw a trouble from this bug. Isn't this merged?

**Comment by edbo** [comment]
Yeah this really needs to get merged. Can we also get the version number bumped when this comes in? I've always been running 0.10.1 which has been working and break on and off for quite a while because the code is always different every time you do a fresh install.

**Comment by rambler** [comment]
+1

**Comment by damacus** [comment]
## Closing due to inactivity. 

If this is still an issue please reopen or open another PR. 

Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Pull request closed without merging**
