### PR TITLE
Chef 12.9+ Resources

### PR DESCRIPTION
**Pull request by martinisoft**
### Description

This PR re-writes the entire cookbook to use Chef 12.7+ resources to vastly simplify the cookbook and move away from recipe and databag based setup. The ultimate plan is to get this merged and stable, then transfer it to the Sous Chefs where it can be properly maintained.

### Issues Resolved

Closes the vast majority of issues.

### Check List

- [ ] New test suite
- [ ] Remove all recipes
- [ ] Install resource
- [ ] Documentation Updates

### CODE REVIEW

**Comment by martinisoft** [comment]
I have updated the original posting with some clarification about eliminating the rvm gem as a dependency. From the RVM maintainers themselves, this was not a solid dependency choice and simply leveraging the CLI is the way to go. I'm also drawing inspiration from [rvm1-ansible](https://github.com/rvm/rvm1-ansible) as well.

**Comment by martinisoft** [comment]
Slowly cleaning up and updating this PR to be a total rewrite. Can't really do small or even backward compatible changes at this point so I am going to assume Chef 12.9+ and go from there. I also plan to hand this cookbook over to the capable hands of the sous-chefs who can better maintain it than just me.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by martinisoft** [comment]
> Hi there! Any news?

None to report. I'll be at ChefConf in a couple days and might hack on this while there. I need to re-target to Chef 13.9+ since 12 is now EOL. The intention now after this is completed is to hand the cookbook over to the Sous Chefs to get a steady group of maintainers. Everyone who has offered at this point has bowed out and thus I am back to being the one and only on this cookbook again.

**Comment by n-rodriguez** [comment]
Hi! Thanks for your answer. I finally wrote my own RVM recipe as I don't need to manage complex configurations like you do. Thank you!

**Comment by damacus** [comment]
Thanks for this @martinisoft I know it's not complete or custom resources. But it gets us a lot closer to what the cookbook needs to look like.

**Pull request merged**
