### PR TITLE
Making vagrant user configurable

### PR DESCRIPTION
**Pull request by danvalencia**
Adding support for overriding vagrant user.

### CODE REVIEW

**Comment by brodock** [comment]
+1 this is a must if you want to support "vagrant-aws" plugin. As an example, the AMI image I'm using, the default user is "ubuntu".

**Comment by brodock** [comment]
@martinisoft I will have some free time on the following days, and can send a PR, if you agree with the issue.

**Comment by martinisoft** [comment]
@brodock this sounds like a candidate patch for the 0.9.x series if you'd like to work against that. Not sure it would still have a place in the LWRP rewrite.

**Comment by damacus** [comment]
## Closing due to inactivity. 

If this is still an issue please reopen or open another PR. 

Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Pull request closed without merging**
