### PR TITLE
Added a way to setup gpg key for user installs.

### PR DESCRIPTION
**Pull request by akshah123**
This PR should address the issue #288

### CODE REVIEW

**Comment by martinisoft** [comment]
I'll take a look at this in the morning @akshah123 

Do you have any tests that could go with this?

**Comment by akshah123** [comment]
@martinisoft my cookbook unit test skills are non-existent at the moment. If tests are a must, let me know and I will try to put something together.

**Comment by cmluciano** [comment]
Can you pull from master and see if this works for you @akshah123 ?

**Comment by akshah123** [comment]
@cmluciano master has some problems.  I have created another PR here to fix them: https://github.com/martinisoft/chef-rvm/pull/328 & https://github.com/martinisoft/chef-rvm/pull/327

**Comment by damacus** [comment]
## Closing due to inactivity. 

If this is still an issue please reopen or open another PR. 

Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Pull request closed without merging**
